name: mundolimpiotheme
display_name: Mundo Limpio Theme
version: 1.0.0
author:
  name: "Byron Briones"
  email: "contacto@bbrion.es"
  url: "https://bbrion.es"

meta:
  compatibility:
    from: 1.7.6
    to: ~ # Compatible with future versions as well

  available_layouts: # Inherited from classic, can be overridden if needed
    layout-full-width:
      name: Full Width
      description: "No side columns, ideal for distraction-free pages such as product pages."
    layout-both-columns:
      name: Three Columns
      description: "One large central column and 2 side columns."
    layout-left-column:
      name: Two Columns, small left column
      description: "Two columns with a small left column"
    layout-right-column:
      name: Two Columns, small right column
      description: "Two columns with a small right column"

assets: # Define assets - CSS and JS files
  css:
    all: # For all pages
      - id: mundolimpio-style # Unique ID for your main theme CSS
        path: assets/css/theme.css
        media: all
        priority: 200 # Higher priority to override parent theme styles
      - id: mundolimpio-custom # For user's custom CSS overrides
        path: assets/css/custom.css
        media: all
        priority: 210
  js:
    all: # For all pages
      - id: mundolimpio-scripts # Unique ID for your main theme JS
        path: assets/js/theme.js
        priority: 200
        position: bottom # Load at the end of the body
      # Posible inclusión de la fuente Montserrat desde Google Fonts
      # - id: montserrat-font
      #   path: https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap
      #   server: remote
      #   media: all
      #   priority: 10 # Cargar antes que nuestro theme.css

parent: classic # Specifies that this is a child theme of 'classic'

layouts:
  # By default, layouts are inherited from the 'classic' parent theme.
  # You can override specific page layouts here if needed.
  # For example, to make the homepage full width by default:
  index: layout-full-width
  # category: layout-left-column
  # product: layout-full-width
  # cms: layout-left-column

# global_settings:
  # This section can be used to define settings manageable via the Theme Customizer in BO.
  # Example:
  #   colors:
  #     primary:
  #       label: "Primary Color"
  #       type: "color"
  #       value: "#007bff" # Default value
  #       description: "Main color for buttons and links."
  #   font:
  #     primary_font:
  #       label: "Primary Font"
  #       type: "text" # Could be select if limited options
  #       value: "'Roboto', sans-serif"
  # image_formats:
  #   # Define custom image formats or override existing ones
  #   product_miniature:
  #     width: 300
  #     height: 300
  #     scope: [products]

# dependencies:
  # List modules that this theme depends on.
  # modules:
  #   - ps_imageslider
  #   - ps_customtext
# hooks:
  # Register custom hooks for your theme if needed
  # displayCustomHomeBlock:
  #   name: displayCustomHomeBlock
  #   title: Custom Home Block
  #   description: Hook for a custom block on the homepage.
  #   page: index
  #   position: 1
# Demo pages (for theme preview in BO)
# demo_pages:
#   product_url: '#' # URL to a sample product page for preview
#   category_url: '#' # URL to a sample category page
#   cms_url: '#' # URL to a sample CMS page
#   index_url: '#' # URL to the homepage

# Options for the theme configurator (if you build one)
# configurator:
#   logo_url: assets/img/logo-configurator.png
#   favicon_url: assets/img/favicon-configurator.png

# Defines if the theme uses the new product page experimental feature
# use_ પણ_product_page_v2: true

# Defines if the theme uses the new checkout page experimental feature
# use_ પણ_checkout_v2: true

# Specifies the default font for the theme
# default_font: "Open Sans"

# Specifies assets to exclude from the parent theme
# parent_assets_to_exclude:
#   css:
#     - id: classic-style # Example: exclude classic's main CSS
#   js:
#     - id: classic-scripts # Example: exclude classic's main JS
