# Mundo Limpio Theme Configuration
# Additional theme-specific configurations

# Theme Information
theme:
  name: "Mundo Limpio Theme"
  version: "1.0.0"
  description: "Tema child optimizado para tienda de productos de limpieza sustentables"
  author: "Mundo Limpio"
  license: "Proprietary"

# Development Settings
development:
  debug_mode: false
  show_template_names: false
  cache_enabled: true
  minify_assets: true
  
# Image Settings
images:
  webp_enabled: true
  lazy_loading: true
  placeholder_color: "#f3f4f6"
  quality:
    jpg: 85
    webp: 80
  sizes:
    thumbnail: [150, 150]
    small: [300, 300]
    medium: [600, 600]
    large: [1200, 1200]
    hero: [1920, 1080]

# Performance Settings
performance:
  enable_css_critical: true
  enable_js_defer: true
  enable_preload: true
  enable_prefetch: true
  cache_duration: 3600 # 1 hour

# SEO Settings
seo:
  meta_title_suffix: " - Mundo Limpio"
  meta_description_length: 160
  enable_breadcrumbs: true
  enable_schema_markup: true
  og_image_default: "assets/img/og-default.jpg"
  
# Social Media
social:
  facebook:
    app_id: ""
    page_url: "https://facebook.com/mundolimpio"
  instagram:
    username: "mundolimpio"
  twitter:
    handle: "@mundolimpio"
  whatsapp:
    number: "+5493764123456"

# Contact Information
contact:
  company_name: "Mundo Limpio"
  address:
    street: "Dirección de la tienda"
    city: "Posadas"
    state: "Misiones"
    country: "Argentina"
    postal_code: "3300"
  phone: "+54 9 3764 12-3456"
  email: "info@mundolimpio.com"
  hours:
    monday: "08:00-18:00"
    tuesday: "08:00-18:00"
    wednesday: "08:00-18:00"
    thursday: "08:00-18:00"
    friday: "08:00-18:00"
    saturday: "08:00-13:00"
    sunday: "closed"

# Feature Flags
features:
  enable_wishlist: true
  enable_compare: true
  enable_reviews: true
  enable_quick_view: true
  enable_ajax_cart: true
  enable_infinite_scroll: false
  enable_filter_sidebar: true
  enable_live_search: true

# Homepage Sections
homepage:
  sections:
    hero:
      enabled: true
      order: 1
    categories:
      enabled: true
      order: 2
      show_count: 6
    featured_products:
      enabled: true
      order: 3
      show_count: 8
    about:
      enabled: true
      order: 4
    values:
      enabled: true
      order: 5
    testimonials:
      enabled: true
      order: 6
      show_count: 6
    stats:
      enabled: true
      order: 7
    cta:
      enabled: true
      order: 8
    newsletter:
      enabled: true
      order: 9

# Product Settings
products:
  show_reference: true
  show_condition: true
  show_availability: true
  show_delivery_time: true
  enable_zoom: true
  enable_thumbnails: true
  reviews_per_page: 10
  related_products_count: 4

# Category Settings
categories:
  products_per_page: 12
  enable_filters: true
  enable_sorting: true
  default_sort: "name_asc"
  available_sorts:
    - "name_asc"
    - "name_desc"
    - "price_asc"
    - "price_desc"
    - "date_add_desc"
    - "date_add_asc"

# Cart Settings
cart:
  enable_cross_selling: true
  cross_selling_count: 4
  enable_abandoned_cart: true
  enable_cart_rules_info: true

# Checkout Settings
checkout:
  enable_guest_checkout: true
  enable_terms_agreement: true
  require_phone: false
  enable_newsletter_optin: true

# Email Settings
emails:
  logo_width: 200
  logo_height: 100
  header_color: "#16a34a"
  footer_color: "#1f2937"

# Multi-language Settings
languages:
  default: "es"
  available:
    - "es"
    - "en"
  show_flags: true
  show_language_selector: true

# Currency Settings
currencies:
  default: "ARS"
  available:
    - "ARS"
    - "USD"
  show_currency_selector: false

# Shipping Settings
shipping:
  show_delivery_time: true
  show_shipping_cost: true
  free_shipping_threshold: 5000 # ARS

# Payment Settings
payments:
  show_accepted_payments: true
  accepted_methods:
    - "visa"
    - "mastercard"
    - "american_express"
    - "mercadopago"

# Analytics Settings
analytics:
  google_analytics_id: ""
  facebook_pixel_id: ""
  google_tag_manager_id: ""

# Custom CSS Variables
css_variables:
  primary_color: "#16a34a"
  primary_light: "#22c55e"
  primary_dark: "#15803d"
  secondary_color: "#dcfce7"
  accent_color: "#f59e0b"
  text_primary: "#1f2937"
  text_secondary: "#6b7280"
  border_color: "#e5e7eb"
  success_color: "#10b981"
  warning_color: "#f59e0b"
  error_color: "#ef4444"
  info_color: "#3b82f6"

# Custom Fonts
fonts:
  primary_family: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
  heading_family: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
  mono_family: "'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"

# Responsive Breakpoints
breakpoints:
  xs: "0px"
  sm: "640px"
  md: "768px"
  lg: "1024px"
  xl: "1280px"
  "2xl": "1536px"

# Error Pages
error_pages:
  404:
    title: "Página no encontrada"
    message: "La página que buscas no existe o ha sido movida."
    show_search: true
    show_categories: true
  500:
    title: "Error interno del servidor"
    message: "Estamos experimentando problemas técnicos. Por favor, inténtelo más tarde."
    show_contact: true

# Maintenance Mode
maintenance:
  enabled: false
  title: "Sitio en mantenimiento"
  message: "Estamos mejorando nuestro sitio. Volvemos pronto."
  estimated_time: "2 horas"
  show_countdown: false

# Security Settings
security:
  enable_csrf_protection: true
  enable_ssl_redirect: true
  enable_security_headers: true
  session_timeout: 1800 # 30 minutes

# Backup Settings
backup:
  auto_backup: false
  backup_frequency: "weekly"
  backup_retention: 30 # days
  include_database: true
  include_files: true